# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaSayfa.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setMinimumSize(QtCore.QSize(450, 600))
        MainWindow.setMaximumSize(QtCore.QSize(450, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 421, 25))
        self.label.setMinimumSize(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lneBoy = QtWidgets.QLineEdit(self.centralwidget)
        self.lneBoy.setGeometry(QtCore.QRect(210, 110, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lneBoy.setFont(font)
        self.lneBoy.setObjectName("lneBoy")
        self.btnHesapla = QtWidgets.QPushButton(self.centralwidget)
        self.btnHesapla.setGeometry(QtCore.QRect(100, 300, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnHesapla.setFont(font)
        self.btnHesapla.setObjectName("btnHesapla")
        self.cmbFormul = QtWidgets.QComboBox(self.centralwidget)
        self.cmbFormul.setGeometry(QtCore.QRect(210, 60, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cmbFormul.setFont(font)
        self.cmbFormul.setObjectName("cmbFormul")
        self.cmbFormul.addItem("")
        self.cmbFormul.addItem("")
        self.cmbFormul.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 110, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lneKilo = QtWidgets.QLineEdit(self.centralwidget)
        self.lneKilo.setGeometry(QtCore.QRect(210, 160, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lneKilo.setFont(font)
        self.lneKilo.setObjectName("lneKilo")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 160, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lneYas = QtWidgets.QLineEdit(self.centralwidget)
        self.lneYas.setGeometry(QtCore.QRect(210, 210, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lneYas.setFont(font)
        self.lneYas.setObjectName("lneYas")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 210, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(100, 260, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cmbCinsiyet = QtWidgets.QComboBox(self.centralwidget)
        self.cmbCinsiyet.setGeometry(QtCore.QRect(210, 260, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cmbCinsiyet.setFont(font)
        self.cmbCinsiyet.setObjectName("cmbCinsiyet")
        self.cmbCinsiyet.addItem("")
        self.cmbCinsiyet.addItem("")
        self.cmbCinsiyet.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(100, 350, 110, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lneBMH = QtWidgets.QLineEdit(self.centralwidget)
        self.lneBMH.setGeometry(QtCore.QRect(210, 350, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lneBMH.setFont(font)
        self.lneBMH.setReadOnly(True)
        self.lneBMH.setObjectName("lneBMH")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmbFormul.setCurrentIndex(2)
        self.cmbCinsiyet.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Bazal Metabolizma Hızı Hesapla"))
        self.btnHesapla.setText(_translate("MainWindow", "HESAPLA"))
        self.cmbFormul.setItemText(0, _translate("MainWindow", "Harris Benedict"))
        self.cmbFormul.setItemText(1, _translate("MainWindow", "Schoffield"))
        self.cmbFormul.setItemText(2, _translate("MainWindow", "Seçiniz"))
        self.label_2.setText(_translate("MainWindow", "Formül:"))
        self.label_3.setText(_translate("MainWindow", "Boy:"))
        self.label_4.setText(_translate("MainWindow", "Kilo:"))
        self.label_5.setText(_translate("MainWindow", "Yaş:"))
        self.label_6.setText(_translate("MainWindow", "Cinsiyet:"))
        self.cmbCinsiyet.setItemText(0, _translate("MainWindow", "Kadın"))
        self.cmbCinsiyet.setItemText(1, _translate("MainWindow", "Erkek"))
        self.cmbCinsiyet.setItemText(2, _translate("MainWindow", "Seçiniz"))
        self.label_7.setText(_translate("MainWindow", "BMH:"))

